### ISSUE TITLE
personal page won't work

### ISSUE THREAD

**Issue by dappledaily** [0xnan-dev/depub#7]
e.g.
https://depub.space/users?account=cosmos1quuhdl6jj049y0fqh8wa46a43gdax7umv25zqc

`ipfs resolve -r /ipns/depub.space/users: no link named "users" under QmcaMikayUhbBdDxejj3H6PmYY99qEH65vEz5FgcT4cNaf`

expected result: https://depub.space/cosmos1quuhdl6jj049y0fqh8wa46a43gdax7umv25zqc

shows posts of cosmos1quuhdl6jj049y0fqh8wa46a43gdax7umv25zqc

**Comment by 0xtaipoian** [comment]
Fixed

**Comment by 0xtaipoian** [comment]
the query by owner result is different to query by fingerprint, still investigating...
